apiVersion: v1
kind: Pod
metadata:
  name: <name>
  labels:
    run: <name>

spec:
  containers:
    -
      name: <name>
      image: 'dockerregistry-rsnpk.vip.slc07.dev.ebayc3.com:5000/bolt-bdd-cucumberjs:3eef69ea25edf5d55f8ee17e7adc1de0404e6ed9'
      command:
        - '/src/docker/entrypoint.sh'
      env:
        -
          name: pandaren_name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      resources:
        limits:
          memory: 1Gi
          cpu: '1'
        requests:
          memory: 100Mi
          cpu: '0.5'
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  restartPolicy: Never
  volumes:
    - name: dshm
      hostPath:
        path: /dev/shm
        type: Directory
